version: '3'
services:
  airflow:
    image: apache/airflow:2.10.2
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:v3rysecur&pas5w0rd@db:5432/banvic
      AIRFLOW__CORE__FERNET_KEY: 'wj6GP7Tixesn_lTcyr4PtkjCipNkT6spQXmXyMDAHtY='
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - 8080:8080
    depends_on:
      - db
    command: webserver

  scheduler:
    image: apache/airflow:2.10.2
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data_engineer:v3rysecur&pas5w0rd@db:5432/banvic
      AIRFLOW__CORE__FERNET_KEY: 'GENERATE_A_KEY'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    depends_on:
      - airflow
      - db
    command: scheduler

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: banvic
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: v3rysecur&pas5w0rd
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./sql/banvic.sql:/docker-entrypoint-initdb.d/banvic.sql
    ports:
      - 55432:5432
